name: "home moviedb"
networks: 
  movie:
services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    # ports: 
    secrets:
      - db_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MONGO_INITDB_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - movie
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    secrets:
      - db_password
    environment:
      - MONGO_URI=mongodb://${DB_ROOT_USER}:${DB_PASSWORD}@db:27017/${DB_NAME}?authSource=admin
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
    - movie

volumes:
  mongo_data:

secrets:
  db_password:
    environment: DB_PASSWORD  # Pulls from .env / shell env